In [106]:
#-*- coding: utf-8 -*-


# 주식 데이터를 이용해 다음날 종가 예측

import pandas as pd

from sklearn.preprocessing import MinMaxScaler

file_data = pd.read_csv('D:/study/keras/0801/data/kospi200test.csv', encoding='euc-kr')

print(file_data.head())




           일자       시가       고가       저가       종가     거래량  환율(원/달러)  \
0  2019/07/31  2036.46  2041.16  2010.95  2024.55  589386    1183.1   
1  2019/07/30  2035.32  2044.59  2032.61  2038.68  547029    1181.6   
2  2019/07/29  2059.13  2063.13  2025.01  2029.48  608670    1183.5   
3  2019/07/26  2063.35  2068.16  2054.64  2066.26  589074    1184.8   
4  2019/07/25  2085.67  2088.81  2061.08  2074.48  598634    1181.5   

   Unnamed: 7  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  


In [107]:
file_data.head()


일자       시가       고가       저가       종가     거래량  환율(원/달러)  \
0  2019/07/31  2036.46  2041.16  2010.95  2024.55  589386    1183.1   
1  2019/07/30  2035.32  2044.59  2032.61  2038.68  547029    1181.6   
2  2019/07/29  2059.13  2063.13  2025.01  2029.48  608670    1183.5   
3  2019/07/26  2063.35  2068.16  2054.64  2066.26  589074    1184.8   
4  2019/07/25  2085.67  2088.81  2061.08  2074.48  598634    1181.5   

   Unnamed: 7  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN

In [108]:
file_data.drop('Unnamed: 7' ,axis=1, inplace=True)

file_data.head()

일자       시가       고가       저가       종가     거래량  환율(원/달러)
0  2019/07/31  2036.46  2041.16  2010.95  2024.55  589386    1183.1
1  2019/07/30  2035.32  2044.59  2032.61  2038.68  547029    1181.6
2  2019/07/29  2059.13  2063.13  2025.01  2029.48  608670    1183.5
3  2019/07/26  2063.35  2068.16  2054.64  2066.26  589074    1184.8
4  2019/07/25  2085.67  2088.81  2061.08  2074.48  598634    1181.5

In [109]:
file_data=file_data.sort_values(by=['일자']) # 시간순으로 정렬

In [110]:
file_data.head()

일자       시가       고가       저가       종가     거래량  환율(원/달러)
598  2017/02/17  2072.57  2081.18  2072.57  2080.58  301517    1146.3
597  2017/02/20  2084.16  2085.59  2077.13  2084.39  297203    1147.5
596  2017/02/21  2085.97  2108.48  2085.00  2102.93  292539    1146.1
595  2017/02/22  2106.42  2108.98  2101.56  2106.61  312219    1142.6
594  2017/02/23  2106.15  2108.99  2103.11  2107.63  430850    1137.3

In [111]:
file_data.drop('일자', axis=1, inplace=True)
file_data

시가       고가       저가       종가      거래량  환율(원/달러)
598  2072.57  2081.18  2072.57  2080.58   301517    1146.3
597  2084.16  2085.59  2077.13  2084.39   297203    1147.5
596  2085.97  2108.48  2085.00  2102.93   292539    1146.1
595  2106.42  2108.98  2101.56  2106.61   312219    1142.6
594  2106.15  2108.99  2103.11  2107.63   430850    1137.3
593  2106.43  2107.83  2090.05  2094.12   385394    1131.5
592  2095.47  2097.24  2084.08  2085.52   343702    1133.7
591  2087.26  2094.41  2084.36  2091.64   399821    1130.7
590  2105.19  2112.58  2096.31  2102.65   434713    1141.6
589  2090.92  2091.59  2072.09  2078.75   425935    1156.1
588  2073.20  2083.80  2067.68  2081.36   431445    1158.0
587  2080.77  2096.79  2079.16  2094.05   277830    1146.1
586  2092.27  2101.56  2088.19  2095.41   381441    1145.5
585  2098.29  2100.08  2090.73  2091.06   408229    1158.1
584  2088.67  2102.05  2082.31  2097.35   500860    1157.4
583  2102.37  2122.88  2100.91  2117.59   382129    1144.4
582  2127.12  2135.50  2124.42  2133.78   365074    1148.8
581  2128.42  2135.38  2127.26  2133.00   374699    1143.6
580  2154.98  2156.85  2143.01  2150.08   402424    1132.0
579  2150.47  2164.59  2148.86  2164.58   302788    1130.9
578  2160.32  2160.57  2151.51  2157.01   264946    1120.1
577  2162.95  2181.99  2160.25  2178.38   303940    1120.3
576  2159.97  2170.00  2158.96  2168.30   394425    1123.3
575  2174.09  2182.42  2170.56  2172.72   358607    1122.4
574  2171.36  2179.34  2163.34  2168.95   358673    1122.6
573  2161.17  2165.25  2153.14  2155.66   395862    1112.8
572  2166.58  2169.14  2157.71  2163.31   393970    1113.0
571  2172.31  2172.31  2162.04  2166.98   626792    1114.2
570  2170.18  2174.16  2159.16  2164.64   643563    1117.2
569  2166.62  2166.93  2159.80  2160.23   441640    1118.4
..       ...      ...      ...      ...      ...       ...
29   2121.78  2131.77  2120.42  2131.29  1007158    1162.1
28   2132.38  2132.68  2120.15  2125.62   692027    1164.0
27   2130.32  2134.48  2123.88  2126.33   669639    1156.5
26   2125.74  2136.24  2115.11  2121.64   642999    1156.2
25   2120.20  2128.25  2115.72  2121.85   736851    1156.6
24   2120.73  2141.27  2118.22  2134.32   644900    1158.1
23   2135.06  2139.24  2123.97  2130.62   537274    1154.7
22   2147.24  2147.24  2126.87  2129.74   412291    1158.8
21   2122.07  2130.86  2112.52  2122.02   460830    1166.0
20   2120.75  2127.71  2093.32  2096.02   522709    1171.3
19   2102.36  2108.80  2088.97  2108.73   446932    1168.6
18   2111.00  2115.43  2096.23  2110.59   459391    1170.4
17   2091.91  2092.54  2063.78  2064.17   515950    1182.0
16   2070.35  2075.30  2052.03  2052.03   440122    1180.5
15   2061.55  2068.20  2056.48  2058.78   355677    1181.6
14   2070.59  2088.24  2070.21  2080.58   376675    1173.5
13   2083.53  2090.43  2077.35  2086.66   403935    1179.2
12   2083.39  2088.34  2073.10  2082.48   463519    1179.3
11   2084.46  2096.67  2078.74  2091.87   682802    1177.6
10   2079.91  2080.01  2063.49  2072.92   761626    1181.3
9    2068.66  2073.20  2061.33  2066.55   446644    1178.8
8    2080.21  2096.73  2076.51  2094.36   394904    1174.5
7    2090.35  2099.34  2087.51  2093.34   332629    1178.3
6    2095.76  2106.39  2095.38  2101.45   648123    1178.9
5    2097.16  2105.68  2080.66  2082.30   851392    1177.9
4    2085.67  2088.81  2061.08  2074.48   598634    1181.5
3    2063.35  2068.16  2054.64  2066.26   589074    1184.8
2    2059.13  2063.13  2025.01  2029.48   608670    1183.5
1    2035.32  2044.59  2032.61  2038.68   547029    1181.6
0    2036.46  2041.16  2010.95  2024.55   589386    1183.1

[599 rows x 6 columns]

In [114]:
price = file_data.values[:,:-1]   # 환율을 빼고 정규화
scaler = MinMaxScaler()
scaler.fit(price)
mm_price = scaler.transform(price)
mm_price

array([[0.14330146, 0.11690231, 0.14599847, 0.14372446, 0.14256465],
       [0.1624756 , 0.12430735, 0.15356041, 0.1500273 , 0.13732264],
       [0.16547001, 0.16274306, 0.16661139, 0.18069778, 0.13165534],
       ...,
       [0.12106674, 0.08659368, 0.06712879, 0.05919039, 0.51579103],
       [0.08167621, 0.05546227, 0.07973202, 0.07440983, 0.4408901 ],
       [0.08356219, 0.04970279, 0.04381281, 0.05103476, 0.49235875]])

In [115]:
volume = file_data.values[:,-1:]   # 환율 정규화
scaler.fit(volume)
mm_volume = scaler.transform(volume)
mm_volume

array([[0.65088339],
       [0.65936396],
       [0.64946996],
       [0.62473498],
       [0.58727915],
       [0.54628975],
       [0.56183746],
       [0.54063604],
       [0.61766784],
       [0.72014134],
       [0.7335689 ],
       [0.64946996],
       [0.64522968],
       [0.73427562],
       [0.72932862],
       [0.63745583],
       [0.66855124],
       [0.63180212],
       [0.54982332],
       [0.54204947],
       [0.46572438],
       [0.46713781],
       [0.48833922],
       [0.4819788 ],
       [0.48339223],
       [0.41413428],
       [0.4155477 ],
       [0.42402827],
       [0.44522968],
       [0.45371025],
       [0.43180212],
       [0.47844523],
       [0.49611307],
       [0.55830389],
       [0.56749117],
       [0.62190813],
       [0.64734982],
       [0.61625442],
       [0.5335689 ],
       [0.60636042],
       [0.59010601],
       [0.62332155],
       [0.60777385],
       [0.604947  ],
       [0.56678445],
       [0.53498233],
       [0.50318021],
       [0.501

In [118]:
import numpy as np
x = np.concatenate((mm_price, mm_volume), axis=1)
x

array([[0.14330146, 0.11690231, 0.14599847, 0.14372446, 0.14256465,
        0.65088339],
       [0.1624756 , 0.12430735, 0.15356041, 0.1500273 , 0.13732264,
        0.65936396],
       [0.16547001, 0.16274306, 0.16661139, 0.18069778, 0.13165534,
        0.64946996],
       ...,
       [0.12106674, 0.08659368, 0.06712879, 0.05919039, 0.51579103,
        0.91378092],
       [0.08167621, 0.05546227, 0.07973202, 0.07440983, 0.4408901 ,
        0.90035336],
       [0.08356219, 0.04970279, 0.04381281, 0.05103476, 0.49235875,
        0.91095406]])

In [90]:
y = x[:,3]
y

array([0.14372446, 0.1500273 , 0.18069778, 0.18678555, 0.18847293,
       0.16612351, 0.15189664, 0.16202088, 0.18023458, 0.14069712,
       0.14501481, 0.16600771, 0.16825754, 0.16106139, 0.17146686,
       0.20494963, 0.23173253, 0.23044219, 0.25869741, 0.28268458,
       0.27016162, 0.30551374, 0.28883853, 0.29615047, 0.28991381,
       0.26792834, 0.28058363, 0.28665487, 0.28278383, 0.27548843,
       0.28753164, 0.27692766, 0.27651409, 0.26311436, 0.26142699,
       0.23097156, 0.21530546, 0.22367616, 0.25626561, 0.23355225,
       0.25155089, 0.25601747, 0.23937534, 0.25715893, 0.28344555,
       0.29783785, 0.33606842, 0.35424904, 0.35692898, 0.35027875,
       0.37381925, 0.40950223, 0.4947311 , 0.45727804, 0.50070307,
       0.4835812 , 0.49124055, 0.49898261, 0.49526047, 0.48490463,
       0.48765075, 0.51337491, 0.52612946, 0.53539347, 0.57772668,
       0.59819021, 0.59433572, 0.57896739, 0.58508826, 0.58050588,
       0.6253536 , 0.62022531, 0.60619696, 0.61187116, 0.64184

In [101]:
data_x = []
data_y = []

for i in range(0, len(y) - 5):
    data_x.append(x[i:i+5])
    data_y.append(y[i+5])
    
data_x = np.array(data_x)
data_y = np.array(data_y)

print(data_x.shape)
data_y.shape

(594, 5, 6)


(594,)

In [104]:
from sklearn.model_selection import train_test_split

train_x, test_x , train_y, test_y = train_test_split(
    data_x, data_y, random_state = 81, test_size=0.4
)

val_x, test_x ,val_y, test_y = train_test_split(
    test_x, test_y, random_state = 81, test_size = 0.5
)

print(train_x.shape)
print(train_y.shape)
print('-'*10)
print(test_x.shape)
print(test_y.shape)
print('-'*10)
print(val_x.shape)
print(val_y.shape)


(356, 5, 6)
(356,)
----------
(119, 5, 6)
(119,)
----------
(119, 5, 6)
(119,)
